name: dynamic_util
description: Dynamic util
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  common: any
  core: any
  flutter_secure_storage: 9.2.2