name: kmpo_invent
description: A invent Flutter project.

publish_to: 'none'

version: 1.0.6

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  common: any
  core: any

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.4
  qr_flutter: ^4.1.0
  barcode_scan2: ^4.3.3
  provider: ^6.1.2
  share_plus: ^10.0.2
  intl: ^0.19.0
  syncfusion_flutter_xlsio: ^27.1.50
  open_file: ^3.5.6
  file_picker: ^8.1.2
  excel: ^3.0.0
  parse_server_sdk: any
  parse_server_sdk_flutter: any
  toastification: ^2.3.0
  flutter_sticky_header: ^0.6.5
  flutter_launcher_icons: ^0.13.1
  pdf: ^3.11.1
  scroll_to_index: ^3.0.1
  flutter_local_notifications: ^17.2.3
  timezone: 0.9.4
  flutter_timezone: 2.0.1
  flutter_platform_widgets: ^7.0.0

dev_dependencies:
  flutter_lints: ^1.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#A30236"
  adaptive_icon_foreground: "assets/logo_droid.png"
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/icona.png
    - assets/images/20.png
    - assets/images/21.png
    - assets/images/22.png
    - assets/images/23.png
    - assets/images/24.png
    - assets/images/25.png
    - assets/images/26.png
    - assets/images/27.png
    - assets/images/29.png
    - assets/images/30.png
    - assets/images/31.png
    - assets/images/32.png
    - assets/images/33.png
    - assets/images/34.png
    - assets/images/35.png
    - assets/images/36.png
    - assets/images/40.png
    - assets/images/41.png
  fonts:
    - family: Roboto   
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
          style: normal
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
          weight: 300
          style: normal
    - family: AlsHauss
      fonts:
        - asset: assets/fonts/ALSHauss-Regular.ttf
          weight: 300
          style: normal
    - family: Arial
      fonts:
        - asset: assets/fonts/Arial.ttf
          weight: 300
          style: normal
